branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1

      required_status_checks:
        strict: true
        contexts: []

      enforce_admins: true # enforce all of these settings for administrators too
      restrictions: null # restrict anyone from pushing to main branch
