repository:
  name: react-typescript-template

branches:
  - name: main
    protection:
      required_pull_request_reviews: null

      required_status_checks:
        strict: true
        contexts: []

      enforce_admins: true # enforce all of these settings for administrators too
      restrictions: null # restrictgst anyone from pushing to main branch
